// @ts-check
/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
const config = {
	packageManager: "pnpm",
	plugins: ["@stryker-mutator/vitest-runner"],
	reporters: ["html", "clear-text", "progress"],
	htmlReporter: {
		fileName: "reports/mutation/mutation.html",
	},
	testRunner: "vitest",
	vitest: {
		configFile: "tests/vitest.config.mts",
	},
	coverageAnalysis: "perTest",
	mutate: [
		"src/**/*.ts",
		// Exclude the same files as vitest coverage
		"!**/*.d.ts",
		"!**/node_modules/**",
		"!**/tests/**",
		"!**/dist/**",
		"!**/coverage/**",
		"!src/domain/**/index.ts",
		"!src/types.ts",
		"!src/domain/**/types.ts",
		"!src/openapi.ts",
		"!src/app-meta.ts",
		"!src/index.ts",
		"!src/lib/svg-charts.ts",
		"!src/lib/sat-file-generator.ts",
		"!src/lib/sat-xml-generator.ts",
		"!src/lib/pdf-report-generator.ts",
		"!src/lib/report-aggregator.ts",
		"!src/lib/prisma.ts",
		"!src/routes/catalogs.ts",
		"!src/routes/clients.ts",
		"!src/routes/files.ts",
		"!src/routes/notices.ts",
		"!src/routes/transactions.ts",
		"!src/routes/ubos.ts",
		"!src/routes/uma-values.ts",
		"!src/routes/organization-settings.ts",
		"!src/routes/internal-organization-settings.ts",
		"!src/routes/alert-rules.ts",
		"!src/routes/alerts.ts",
		"!src/routes/imports.ts",
		"!src/routes/reports.ts",
		"!src/middleware/admin-auth.ts",
		"!src/middleware/auth.ts",
		"!src/domain/ubo/schemas.ts",
		"!src/domain/uma/schemas.ts",
		"!src/domain/organization-settings/**",
		"!src/domain/alert/**",
		"!src/domain/report/**",
		"!src/domain/catalog/service.ts",
		"!src/domain/catalog/schemas.ts",
		"!src/domain/transaction/repository.ts",
		"!src/domain/transaction/schemas.ts",
		"!src/domain/transaction/mappers.ts",
		"!src/domain/client/mappers.ts",
		"!src/domain/client/schemas.ts",
		"!src/domain/notice/mappers.ts",
		"!src/domain/notice/schemas.ts",
		"!src/domain/notice/service.ts",
	],
	thresholds: {
		high: 80,
		low: 60,
		break: 50,
	},
	timeoutMS: 60000,
	concurrency: 4,
};
export default config;
