/**
 * Public Upload Routes (token-based, no auth required)
 *
 * These routes allow clients to upload assets using a temporary upload token.
 * The token is generated by an authenticated admin endpoint and is single-use,
 * short-lived (15 min), and unguessable.
 *
 * Security:
 * - Token validates and authorizes the upload independently
 * - Token is deleted after successful upload (single-use)
 * - Expiry is checked to prevent replays of expired tokens
 */

import { Hono } from "hono";

import type { Bindings } from "../types";
import { APIError } from "../middleware/error";
import { uploadToR2 } from "../lib/r2-upload";

export const publicUploadsRouter = new Hono<{ Bindings: Bindings }>();

publicUploadsRouter.put("/asset/:token", async (c) => {
	const token = c.req.param("token");
	const raw = await c.env.CACHE.get(`training:upload:${token}`);
	if (!raw) {
		throw new APIError(400, "Invalid or expired upload token");
	}

	const meta = JSON.parse(raw) as {
		key: string;
		contentType: string;
		exp: number;
	};

	if (Date.now() > meta.exp) {
		throw new APIError(400, "Upload token expired");
	}

	const buf = await c.req.arrayBuffer();

	await uploadToR2({
		bucket: c.env.R2_BUCKET,
		key: meta.key,
		content: buf,
		contentType: meta.contentType,
	});

	await c.env.CACHE.delete(`training:upload:${token}`);

	return c.json({ key: meta.key });
});
