-- Migration: Replace UUID defaults with custom ID generation
-- This migration updates the schema to use custom ID generation instead of UUIDs
-- Note: This migration assumes the Prisma schema has already been updated

-- Step 1: For Client table, add id column if it doesn't exist and migrate data
-- First, check if id column exists (SQLite doesn't support IF NOT EXISTS for columns in ALTER TABLE)
-- We'll create a new table with the correct structure and migrate data

-- Create temporary table for clients with new structure
CREATE TABLE clients_new (
    id TEXT PRIMARY KEY,
    rfc TEXT UNIQUE NOT NULL,
    organizationId TEXT NOT NULL,
    personType TEXT NOT NULL,
    firstName TEXT,
    lastName TEXT,
    secondLastName TEXT,
    birthDate TEXT,
    curp TEXT,
    businessName TEXT,
    incorporationDate TEXT,
    nationality TEXT,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    country TEXT NOT NULL,
    stateCode TEXT NOT NULL,
    city TEXT NOT NULL,
    municipality TEXT NOT NULL,
    neighborhood TEXT NOT NULL,
    street TEXT NOT NULL,
    externalNumber TEXT NOT NULL,
    internalNumber TEXT,
    postalCode TEXT NOT NULL,
    reference TEXT,
    notes TEXT,
    countryCode TEXT,
    economicActivityCode TEXT,
    createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deletedAt TEXT
);

-- Generate IDs for existing clients (using a simple pattern: CLT + random hex)
-- Note: In production, you should use the actual ID generator function
-- For now, we'll use a pattern that's compatible with the new ID format
INSERT INTO clients_new (
    id, rfc, organizationId, personType, firstName, lastName, secondLastName,
    birthDate, curp, businessName, incorporationDate, nationality, email, phone,
    country, stateCode, city, municipality, neighborhood, street, externalNumber,
    internalNumber, postalCode, reference, notes, countryCode, economicActivityCode,
    createdAt, updatedAt, deletedAt
)
SELECT 
    'CLT' || lower(substr(hex(randomblob(9)), 1, 9)) as id,
    rfc, organizationId, personType, firstName, lastName, secondLastName,
    birthDate, curp, businessName, incorporationDate, nationality, email, phone,
    country, stateCode, city, municipality, neighborhood, street, externalNumber,
    internalNumber, postalCode, reference, notes, countryCode, economicActivityCode,
    createdAt, updatedAt, deletedAt
FROM clients;

-- Drop old table and rename new one
DROP TABLE clients;
ALTER TABLE clients_new RENAME TO clients;

-- Recreate indexes
CREATE INDEX IF NOT EXISTS clients_organizationId_idx ON clients(organizationId);
CREATE INDEX IF NOT EXISTS clients_personType_idx ON clients(personType);
CREATE INDEX IF NOT EXISTS clients_deletedAt_idx ON clients(deletedAt);
CREATE INDEX IF NOT EXISTS clients_countryCode_idx ON clients(countryCode);
CREATE INDEX IF NOT EXISTS clients_economicActivityCode_idx ON clients(economicActivityCode);
CREATE INDEX IF NOT EXISTS clients_id_idx ON clients(id);

-- Step 2: Update foreign key references in client_documents
-- Note: SQLite doesn't enforce foreign keys by default, but we update the references
UPDATE client_documents 
SET clientId = (
    SELECT id FROM clients WHERE clients.rfc = client_documents.clientId
)
WHERE EXISTS (
    SELECT 1 FROM clients WHERE clients.rfc = client_documents.clientId
);

-- Step 3: Update foreign key references in client_addresses
UPDATE client_addresses 
SET clientId = (
    SELECT id FROM clients WHERE clients.rfc = client_addresses.clientId
)
WHERE EXISTS (
    SELECT 1 FROM clients WHERE clients.rfc = client_addresses.clientId
);

-- Step 4: Update foreign key references in transactions
UPDATE transactions 
SET clientId = (
    SELECT id FROM clients WHERE clients.rfc = transactions.clientId
)
WHERE EXISTS (
    SELECT 1 FROM clients WHERE clients.rfc = transactions.clientId
);

-- Step 5: Update foreign key references in alerts
UPDATE alerts 
SET clientId = (
    SELECT id FROM clients WHERE clients.rfc = alerts.clientId
)
WHERE EXISTS (
    SELECT 1 FROM clients WHERE clients.rfc = alerts.clientId
);

-- Note: For other tables (ClientDocument, ClientAddress, Transaction, etc.),
-- the IDs will be generated by the application code going forward.
-- Existing UUIDs in those tables will remain valid but new records will use the new ID format.

