import type { Context } from "hono";
import type { PEPJob } from "./lib/pep-queue";

/**
 * Extended environment bindings with custom properties.
 * The base Env is auto-generated by `wrangler types` in worker-configuration.d.ts
 */
export type Bindings = Env & {
	/**
	 * Comma-separated list of trusted origins for CORS.
	 * Example: "https://aml.janovix.com,https://auth.janovix.com,http://localhost:3000"
	 */
	TRUSTED_ORIGINS?: string;
	/** Queue for import processing jobs */
	IMPORT_PROCESSING_QUEUE?: Queue<import("./domain/import").ImportJob>;
	/** Queue for PEP check jobs */
	PEP_CHECK_QUEUE?: Queue<PEPJob>;
	/** Secret token for synthetic data generation HTTP endpoint (local development only) */
	SYNTHETIC_DATA_SECRET?: string;
	/**
	 * Sentry DSN for error tracking.
	 * If not set, Sentry will be disabled.
	 * Configured via Cloudflare Dashboard secrets or wrangler vars.
	 */
	SENTRY_DSN?: string;
	/** 12-character obligated subject identifier (RFC) */
	SAT_CLAVE_SUJETO_OBLIGADO?: string;
	/** Activity code (e.g., "VEH" for vehicle notices) */
	SAT_CLAVE_ACTIVIDAD?: string;
	/** Optional collegiate entity identifier */
	SAT_CLAVE_ENTIDAD_COLEGIADA?: string;
	/** API version override (defaults to package.json version) */
	API_VERSION?: string;
};

export type AppContext = Context<{ Bindings: Bindings }>;
export type HandleArgs = [AppContext];
