import type { Context } from "hono";

/**
 * Extended environment bindings with custom properties.
 * The base Env is auto-generated by `wrangler types` in worker-configuration.d.ts
 */
export type Bindings = Omit<Env, "ENVIRONMENT" | "AUTH_JWKS_CACHE_TTL"> & {
	/** Environment name (dev, preview, production) - overridden to be string instead of literal */
	ENVIRONMENT?: string;
	/** Cache TTL for JWKS in seconds - overridden to be string instead of literal */
	AUTH_JWKS_CACHE_TTL?: string;
	/**
	 * Comma-separated list of trusted origins for CORS.
	 * Example: "https://aml.janovix.com,https://auth.janovix.com,http://localhost:3000"
	 */
	TRUSTED_ORIGINS?: string;
	/** Queue for import processing jobs */
	IMPORT_PROCESSING_QUEUE?: Queue<import("./domain/import").ImportJob>;
	/** Watchlist service binding for automated screening */
	WATCHLIST_SERVICE?: Fetcher;
	/** Notifications service binding for sending emails and real-time notifications */
	NOTIFICATIONS_SERVICE?: Fetcher;
	/** KYC Self-Service app URL for generating invite links */
	KYC_SELF_SERVICE_URL?: string;
	/** Internal service-to-service shared secret */
	INTERNAL_SERVICE_SECRET?: string;
	/** Secret token for synthetic data generation HTTP endpoint (local development only) */
	SYNTHETIC_DATA_SECRET?: string;
	/**
	 * Sentry DSN for error tracking.
	 * If not set, Sentry will be disabled.
	 * Configured via Cloudflare Dashboard secrets or wrangler vars.
	 */
	SENTRY_DSN?: string;
	/** 12-character obligated subject identifier (RFC) */
	SAT_CLAVE_SUJETO_OBLIGADO?: string;
	/** Activity code (e.g., "VEH" for vehicle notices) */
	SAT_CLAVE_ACTIVIDAD?: string;
	/** Optional collegiate entity identifier */
	SAT_CLAVE_ENTIDAD_COLEGIADA?: string;
	/**
	 * CurrencyLayer API key for real-time exchange rates.
	 * Get your key at: https://currencylayer.com/
	 */
	CURRENCYLAYER_API_KEY?: string;
	/** API version override (defaults to package.json version) */
	API_VERSION?: string;
	/**
	 * Cloudflare Worker version metadata.
	 * Used for Sentry release tracking.
	 */
	CF_VERSION_METADATA?: WorkerVersionMetadata;
};

export type AppContext = Context<{ Bindings: Bindings }>;
export type HandleArgs = [AppContext];
